### PR TITLE
Issue #3 - Changed classes to be records

### PR DESCRIPTION
**Pull request by ReyhanPatria**
I changed some classes in the data package to be records. I chose the classes to be converted based on how the previous code declared attributes in the class, I chose classes that declared all the attributes as final. 

Then after converting those classes to records I had to change how other classes retrieved data using the generated getters from records.

### CODE REVIEW

**Review by Majekdor — DISMISSED** [review]
This all looks okay to me. Love all the getters records remove.

**Comment by Majekdor** [comment]
Only looked at the changes in GitHub, not IntelliJ, but it all looks good to me. Waiting for review from the big boss Cassy.

**Review by Majekdor — APPROVED** [review]

**Review by funnyboy-roks — COMMENTED** [review]
This looks good, I'd like to test it before merging, though.

**Review by funnyboy-roks — CHANGES_REQUESTED** [review]
After testing on our dev server, [this error](https://pastebin.com/qJ1WDY3Z) occurred when loading the server's pre-existing data.  You can use [this sample playerdata](https://gist.github.com/funnyboy-roks/03b0b85c8394cf5fcaaa406da404d6ec) to test your code further.

**Comment by ReyhanPatria** [comment]
@funnyboy-roks @Majekdor @Cassy343 So after testing a bit, I found out it's an error from Gson itself not being able to deserialize records properly, it's a [known Gson issue](https://github.com/google/gson/issues/1794). There are workarounds provided by the community, but the simplest fix is just to revert Birthday back to a class.

**Review by funnyboy-roks — APPROVED** [review]

**Pull request merged**
